RAPID_API_BASE_URL = ENV['RAPID_API_BASE_URL']
RAPID_API_KEY = ENV['RAPID_API_KEY']
RAPID_API_HOST = ENV['RAPID_API_HOST']

JWT_ACCOUNT = ENV['JWT_ACCOUNT']
JWT_SECRET_KEY = ENV['JWT_SECRET_KEY']
JWT_EXPIRATION = ENV['JWT_EXPIRATION']
